# Generated by Django 4.2.2 on 2023-07-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('place', models.CharField(max_length=250)),
                ('poems', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
